import assert from 'power-assert'
import retry from '../src/retry'

describe('test retry', () => {
  it('correct promise', async () => {
    // Given
    const correntPromise = () => new Promise((resolve) => setTimeout(() => {
      resolve({ success: true })
    }, 500))
    // Then
    const result = await retry({
      promise: correntPromise,
    })
    assert(result.success)
  })

  it('failed promise', async () => {
    // Given
    const failedPromise = () => new Promise((resolve, reject) => setTimeout(() => {
      reject({ success: false })
    }, 100))
    // Then
    try {
      const result = await retry({
        promise: failedPromise,
      })
      console.log(result)
    } catch (e) {
      assert(!e.success)
    }
  })
})
